name: products_flutter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  moor_flutter: ^3.1.0
  sqlite3_flutter_libs: ^0.2.0
  path_provider:
  path:
  flutter_mobx: ^1.1.0
  moor_ffi:

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator:
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
